# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterIndexTogether(
            name='round',
            index_together=set([('start_time', 'end_time')]),
        ),
        migrations.AlterIndexTogether(
            name='tournament',
            index_together=set([('start_time', 'end_time')]),
        ),
        migrations.AddField(
            model_name='answer',
            name='is_success',
            field=models.NullBooleanField(),
        ),
        migrations.AlterIndexTogether(
            name='task',
            index_together=set([('id', 'correct_answer')]),
        ),
    ]
