# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20170924_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
