# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 07:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_tournament_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ('-points',)},
        ),
        migrations.AlterModelOptions(
            name='round',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='tournament',
            options={'ordering': ('id',)},
        ),
    ]
