# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20171009_0758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={},
        ),
        migrations.AlterField(
            model_name='rating',
            name='points',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='rounds',
            field=models.ManyToManyField(related_name='tasks', to='tasks.Round'),
        ),
    ]
