# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 21:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20171009_2004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'permissions': (('can_create_answer', 'Can create answer'),)},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ('points',)},
        ),
    ]
